### ISSUE TITLE
您好，请问地图「下一页」是什么意思呢

### ISSUE THREAD

**Issue by pavison** [liguobao/58HouseSearch#100]
出行到达圈，「下一页」是什么意思呢

**Comment by liguobao** [comment]
因为数据不止一页呀，默认值出1200条最近的数据，所以那个位置加了下一页。

**Comment by pavison** [comment]
原来如此，所以地图显示的数据也仅是最近 1200 条的数据，想看地图的更多数据，点下一页咯
