### ISSUE TITLE
可以支持标记多个点嘛

### ISSUE THREAD

**Issue by runkid1** [liguobao/58HouseSearch#119]
目前上班地点只支持标记一个，我和室友合租的时候想选取工作位置的相对中间一点的地方

**Comment by runkid1** [comment]
![image](https://user-images.githubusercontent.com/35693632/124408298-7beee580-dd78-11eb-8ef6-a44b0fe0fb70.png)
目前是这样的，想要可以支持标记多个点，标记多个点的时候可以不用计算多个点之间的通勤时间，就是只做标记展示用

**Comment by liguobao** [comment]
多个点的需求，有点蛋疼...
Mark一下，我思考思考。
