### ISSUE TITLE
最好可以选择当前所在城市

### ISSUE THREAD

**Issue by codingstar** [liguobao/58HouseSearch#27]
rt，这样就能异地查看房子了～不然地图数据是上海的，但是地图显示的是当前所在城市的😂

**Comment by liguobao** [comment]
由于没有一个很好的交互思路，所以没有直接开放选择城市功能。
不过在现有的模式，可以通过移动地图来切换城市。

**Comment by liguobao** [comment]
等产品给个方案，再确认如何实现...

**Comment by liguobao** [comment]
已加入豪华套餐...
codelover.link:8080 

or 

yibaobao.wang:8080
