### ISSUE TITLE
用vs打开,出现错误

### ISSUE THREAD

**Issue by youngjeff** [liguobao/58HouseSearch#34]
用vs打开项目.58HouseSearch可以正常运行,但是58HouseSearch.Core不. 如下图所示:

![](http://7xjs0i.com1.z0.glb.clouddn.com/1.png),

但是我已经安装好了 .net core,nuget 包里也是正常的,不知道怎么操作?

**Comment by liguobao** [comment]
https://github.com/liguobao/58HouseSearch/commit/0b49a84eda4fe671d1ffaec5b0fc1c9e1ce35157

已修复
