### ISSUE TITLE
想知道房源地位是如何做到的？

### ISSUE THREAD

**Issue by youngjeff** [liguobao/58HouseSearch#35]
大神好，我看了代码后明白了爬取的数据规则，但是没有看到经纬度，那高德是如何定位的呢？

**Comment by liguobao** [comment]
定位来说，高德地图提供关键字搜索接口的，我这边实现的是直接将文本传入，让它帮我去定位的。
因此有时候会发现定位不准之类的小问题。
不同房源有不同的处理方案，其实58公寓上来说，提供了经纬度的，只是我这边懒得用;上海互助租房因为是用户描述，基本没有地理信息，看代码应该也知道，很粗糙处理了一下之后直接返回给高德了，现在看下来效果也挺好的；豆瓣租房更粗暴，直接传入讨论标题...
上面所有的前提都是，确定了所在城市...因为有了所在城市，定位才能更精准。
在这里我考虑过引入分词API更准确拿到地理位置，后来发现高德API做的好像已经很出色了，所以就没理了....
有兴趣了解更多可以看下高德JS-API:
[http://lbs.amap.com/api/javascript-api/guide/map-data/input_prompt/](http://lbs.amap.com/api/javascript-api/guide/map-data/input_prompt/)
