### ISSUE TITLE
删除 58HouseSearch.Core.csproj 部分节点

### ISSUE THREAD

**Issue by Desmond-Liu** [liguobao/58HouseSearch#48]
删除 58HouseSearch/58HouseSearch.Core/58HouseSearch.Core/58HouseSearch.Core.csproj 里
<ItemGroup> 下所有 <Content> 节点， 否则打开项目后会报错，根据错误提示这些资源文件包涵在了项目引用里。

**Comment by liguobao** [comment]
我晚上确认一下,或者你提一个pull request过来修复也可以.

**Comment by Desmond-Liu** [comment]
使用 vs 版本：
Microsoft Visual Studio Professional 2017 
版本 15.4.3

不确定是否为开发环境的原因， 安装的 .Net Core 2.0，运行这个工程的话需要安装.Net Core 1.0 吗？

**Comment by liguobao** [comment]
大概知道为嘛了,确实是.NET Core版本的问题,我尽快处理一下.

**Comment by liguobao** [comment]
https://github.com/liguobao/58HouseSearch/commit/8bd306ddbf790e73976c2f7b11f3ddcd28697bed
已修复
