### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by 1c7** [liguobao/58HouseSearch#53]
## 两点
1. 把 README 总体改得更加"新人友好"
开头就说清楚这个东西是什么，能解决什么问题
（现在给人的总体感觉是很"乱"）

2.  Changelog 太长了，对大部分用户来说没有马上知道的必要，可以单独放到一个 Changelog.md 文件里
然后 README 文件里放个链接可以点过去就行了

**Comment by 1c7** [comment]
当然，怎样"更好"是个很主观的事情，没有唯一的正确答案，
我这里只是顺口说两句，不用有压力觉得一定要改什么。

此 issue 可随意关闭

**Comment by 1c7** [comment]
祝项目越做越好。
话说现在你每周投入多少时间？
另外可以去 wanqu.io 湾区论坛上面的 side project 板块，还有 v2ex 的分享创造板块。还有 https://github.com/1c7/chinese-independent-developer
发一下。可能会多一点流量

**Comment by liguobao** [comment]
嗯嗯,非常好的建议,我这几天空了整理一下.
SEO全靠自卖自夸了,之前很多地方做的很一般,不怎么好夸自己,所以也就小范围扩散一下.
最近打算有空多搞搞事,先做好网站再想想搞搞分析什么的(这里主要是自己学习为主),希望也能帮到大家.

**Comment by 1c7** [comment]
好

**Comment by 1c7** [comment]
如果英文好，可以去 Indie Hacker 和 Work in Progress 找人聊聊，看看资深 Maker 给什么建议

**Comment by liguobao** [comment]
嗯嗯,谢谢建议...
您这边做得其实比我好多了.

**Comment by liguobao** [comment]
我这边一周投入时间非常动态,有Bug或者需要新功能我就做,不然就放着...
毕竟我也不看这个赚钱,纯粹业余弄弄.

**Comment by 1c7** [comment]
@liguobao  这样，嗯嗯

**Comment by 1c7** [comment]
Hello，我把你的项目 pin 到了 telegram 的一个组里，有人表示有兴趣想沟通下，
https://t.me/fun_makers
如果乐意的话可以加这个群，有3400多人
