### ISSUE TITLE
用户体验建议

### ISSUE THREAD

**Issue by liuyuwang2016** [liguobao/58HouseSearch#63]
您好！

您做的这个真的很棒，但是使用过程有一个小建议，可不可以不要直接进行地图导航，而是按一个按键之后地图导航，不然的话经常会打扰到体验。

谢谢您~

**Comment by liuyuwang2016** [comment]
最好还可以直接选择价位的直接显示该价位的所有房子~~

**Comment by liguobao** [comment]
价位显示房子实现起来倒不难,交互上的逻辑没有很好的思路,所以一直都没做.
我可以先在"高级搜索"里面实现这个价格的功能,这两天加上去吧.

点击时先不要进行导航操作,这个问题我们先保留意见,看看还有没有其他人也有类似的看法?如何?

**Comment by liuyuwang2016** [comment]
感谢你~太棒啦

**Comment by liguobao** [comment]
高级搜索页支持价格搜索已经做好了,导航继续保留意见...

https://github.com/liguobao/58HouseSearch/commit/febf5d4840829a5e392f8128cc6d3a6ebb63ea35

**Comment by liguobao** [comment]
也看到其他小伙伴觉得自动导航让大家使用起来有点别扭,所以这次把导航功能改成了手动的,已经发布上线了.
这个issues我关掉了哈.
https://github.com/liguobao/58HouseSearch/commit/e33faa08b1aca234c07294c9166523ab3e75fef0
