### ISSUE TITLE
可以使用点聚合功能展示点位

### ISSUE THREAD

**Issue by BaiC** [liguobao/58HouseSearch#72]
示例： https://lbs.amap.com/api/javascript-api/example/marker/markerclusterer/

**Comment by liguobao** [comment]
这个最早的时候想过,不过好像要处理一下地址...

**Comment by BaiC** [comment]
不用做处理的，点的经纬度信息有了之后聚合的结果是代码动态生成的

**Comment by liguobao** [comment]
大体明白...
你有空来帮忙写一下么?2333

**Comment by liguobao** [comment]
前端代码很需要重构成react/vue.js之类的,现在jQuery一把梭各种修修补补维护起来太累了.

**Comment by BaiC** [comment]
我前端也是刚入门=。=之前也是leaflet、mapbox这种用的比较多
不过可以试一试

**Comment by liguobao** [comment]
你要不帮我把首页重构一下?233,首页改好了我们再去改地图页,或者直接重写地图页也行.
如果是地图页API的话,直接用
```curl
curl -X POST \
  https://house-map.cn/Home/Houses \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: ef7dd035-1807-19a3-f584-8a0f1e3c0322' \
  -d '{
"cityName":"上海"
}'
```
