### ISSUE TITLE
request

### ISSUE THREAD

**Issue by yttas** [liguobao/58HouseSearch#85]
can you  capture some screenshots?i cannot run the program in my computer,thanks

**Comment by liguobao** [comment]
Sorry,This projectmaybe not is good study project,that depend on many specific config.

If you would to learn to write a crawler on dotnet core ,you can read the project [liguobao/MovieCrawler](https://github.com/liguobao/MovieCrawler).

Thanks.

**Comment by liguobao** [comment]
If you would to run it on you computer,I will push some new SQL Script file to init DB and fix appsettings.json later.

**Comment by liguobao** [comment]
maybe you want to read [半个小时教你写一个装(bi)逼(she)之地图搜租房](https://zhuanlan.zhihu.com/p/37180161)
