### ISSUE TITLE
web page

### ISSUE THREAD

**Issue by yttas** [liguobao/58HouseSearch#86]
the project is a web page?not an application？why i cannot see a prefix with exe?thank you

**Comment by liguobao** [comment]
[House-Map.Crawler](https://github.com/liguobao/58HouseSearch/tree/master/House-Map.Crawler) is dotnet core app.

[House-Map.UI](https://github.com/liguobao/58HouseSearch/tree/master/House-Map.UI) is vue js web page.

**Comment by liguobao** [comment]
[House-Map.Crawler/API](https://github.com/liguobao/58HouseSearch/tree/master/House-Map.Crawler/API) is HTTP  REST API.
