### ISSUE TITLE
所有原地址都刷新不出来

### ISSUE THREAD

**Issue by adolphnov** [liguobao/58HouseSearch#91]
都是这种情况 ![刷新不出来](https://i.loli.net/2019/03/06/5c7f9b92ef548.png)

**Comment by liguobao** [comment]
地址给一下? 
哪个城市呢?

**Comment by liguobao** [comment]
我看上海-豆瓣很正常来的.

https://house-map.cn/#/Map?city=%E4%B8%8A%E6%B5%B7&source=douban_wechat

**Comment by liguobao** [comment]
顺便给一下浏览器和操作系统信息哈.

**Comment by liguobao** [comment]
很奇怪啊, 我这边都是正常的.

**Comment by liguobao** [comment]
能搞掂截图给我看看吗? 邮件发一下截图到我邮箱也行.
