### ISSUE TITLE
想咨询一个非技术问题，爬第三方数据，需要担心法律问题吗？

### ISSUE THREAD

**Issue by jingxinxin** [liguobao/58HouseSearch#92]
一直想做一些类似的爬虫，比较留意这个问题，不知道有没有需要注意的东西，还请大家指点迷津

**Comment by qzcool** [comment]
看你是否商业化使用

**Comment by liguobao** [comment]
参考这个讨论[爬虫究竟是合法还是违法的？](https://www.zhihu.com/question/291554395)
